/**
 * Pet Store API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreatePetDto } from '../model/models';
import { Pet } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PetsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a pet
     * 
     * @param createPetDto 
     */
    petsControllerCreate(createPetDto: CreatePetDto, extraHttpRequestParams?: any): Observable<Pet>;

    /**
     * List all pets
     * 
     * @param limit How many items to return at one time (max 100)
     */
    petsControllerFindAll(limit?: number, extraHttpRequestParams?: any): Observable<Array<Pet>>;

    /**
     * Info for a specific pet
     * 
     * @param id The id of the pet to retrieve
     */
    petsControllerFindOne(id: number, extraHttpRequestParams?: any): Observable<Pet>;

    /**
     * Delete a pet
     * 
     * @param id The id of the pet to delete
     */
    petsControllerRemove(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update a pet
     * 
     * @param id The id of the pet to update
     * @param createPetDto Updated pet data
     */
    petsControllerUpdate(id: number, createPetDto: CreatePetDto, extraHttpRequestParams?: any): Observable<Pet>;

}
